package com.ecommerce.orderservice.orderline;

import com.ecommerce.orderservice.order.Order;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a single line item in a customer order.
 * <p>
 *   Each OrderLine corresponds to a product being purchased,
 *  including the quantity of that product.
 * </p>
 * <p> This is a child entity of {@link Order}, meaning each OrderLine belongs to a single Order.
 *  The relationship is mapped via a foreign key (order_id).
 *  </p>
 *
 * <p>
 *     Example: An order with 2 items will have 2 OrderLine entries in the database.
 * </p>
 */
@AllArgsConstructor
@Builder
@Getter
@Setter
@Entity
@NoArgsConstructor
@Table(name = "customer_line")
public class OrderLine {

    /**
     * The primary key for this OrderLine.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue
    private Integer id;

    /**
     * The parent Order to which this line item belongs.
     *
     * Mapped using a Many-to-One relationship (many lines can belong to one order).
     */
    @ManyToOne
    @JoinColumn(name = "order_id")
    private Order order;

    /**
     * The ID of the product being purchased.
     * This should correspond to the Product ID in the product catalog.
     */
    private Integer productId;

    /**
     * The quantity of this product being purchased in this line item.
     */
    private double quantity;
}
