server:
  port: 8090
spring:
  data:
    mongodb:
      username: mongouser
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin